const fs = require('fs');
const path = require('path');

// Load .env file
const envPath = path.resolve(__dirname, '../.env');
const envContent = fs.readFileSync(envPath, 'utf-8');

// Parse .env file
const envVars = {};
envContent.split('\n').forEach((line) => {
  const trimmed = line.trim();
  if (trimmed && !trimmed.startsWith('#')) {
    const [key, ...valueParts] = trimmed.split('=');
    envVars[key.trim()] = valueParts.join('=').trim();
  }
});

// Generate environment.ts content
const environmentContent = `// This file is auto-generated by scripts/set-env.js
// Do not edit manually - edit .env instead and run: npm run config

export const environment = {
  production: false,
  apiUrl: '${envVars.API_URL}',
};
`;

// Write environment.ts
const outputPath = path.resolve(__dirname, '../src/environments/environment.ts');

// Ensure directory exists
const outputDir = path.dirname(outputPath);
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

fs.writeFileSync(outputPath, environmentContent);

console.log('✅ Environment file generated: src/environments/environment.ts');
